server:
  httpPort: "8082"

infrastructure:
  retry:
    maxAttempts: 10
    delaySeconds: 2

services:
  content:
    grpc:
      addr: "content-service:50051"
    http:
      addr: "http://content-service:8081"
  captcha:
    http:
      addr: "http://captcha-service:8083"

rabbitmq:
  url: "amqp://admin:admin@rabbitmq:5672/"
  topology:
    exchange: "gateway_service.v1.events"
    cv_request_routing_key: "cv.request.password"