server:
  httpPort: "8082"

infrastructure:
  retry:
    maxAttempts: 20
    delaySeconds: 5

services:
  content:
    grpc:
      addr: ""
    http:
      addr: ""

rabbitmq:
  url: ""
  topology:
    exchange: "gateway_service.v1.events"
    cv_request_routing_key: "cv.request.password"